name: MoonLogin
version: ${project.version}
main: me.kp.moon.moonlogin.Main
api-version: 1.8.8
authors: [ pedrokp ]
load: POSTWORLD
softdepend:
  - packetevents
  - ViaVersion
  - ProtocolSupport
  - ProtocolLib
commands:
  loginteste:
    description: testedev
  login:
    description: Login!@#!@#
    aliases:
      - logar
  register:
    description: REgsiter2!
    aliases:
      - registrar
  unregister:
    description: unregsiter!
  forcelogin:
    description: cshseh
  changepassword:
    description: change!!@#
    aliases:
      - mudarsenha